#!/bin/bash

export CUDA_VISIBLE_DEVICES=1

export ROS_PORT_SIM=11312
export ROS_MASTER_URI=http://localhost:${ROS_PORT_SIM}

export VLM_GROUNDING_DINO_PORT=12191
export VLM_BLIP2ITM_PORT=12192
export VLM_MOBILE_SAM_PORT=12193
export VLM_YOLOV7_PORT=12194

echo "环境变量设置完成："
echo "- CUDA_VISIBLE_DEVICES: $CUDA_VISIBLE_DEVICES"
echo "- ROS_PORT_SIM: $ROS_PORT_SIM"
echo "- ROS_MASTER_URI: $ROS_MASTER_URI"
echo "- Grounding DINO: $VLM_GROUNDING_DINO_PORT"
echo "- BLIP2 ITM: $VLM_BLIP2ITM_PORT"
echo "- SAM Segmentor: $VLM_MOBILE_SAM_PORT"
echo "- YOLOv7 Detector: $VLM_YOLOV7_PORT"